[package]
name = "ebb_parsing_framework"
version = "0.1.0"
edition = "2021"
authors = ["mia entropy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-ext = "1.0.1"
